### PR TITLE
Add support for a variant of mpg videos

### PR DESCRIPTION
**Pull request by drimer**
I've added a sample, which is a perfectly valid video. The headers are
000001b3, which is slightly different from the only one that was being
supported.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you link to some docs/source about this?

**Comment by drimer** [comment]
https://en.wikipedia.org/wiki/List_of_file_signatures

The last column to the right has the two possible values. If you'd like, I'm happy to amend the commit message an add this to it.

**Comment by sindresorhus** [comment]
`fixture-mpg.mpg` => `fixture2.mpg`

**Comment by sindresorhus** [comment]
You need to include the extra fixture in the test, like done here: https://github.com/sindresorhus/file-type/blob/4ad8b6e8cd8feab2f827f942d77d34f74e1b5d85/test.js#L105

**Comment by drimer** [comment]
Oh, yeah. I thought it'd be automatically picked up by the tests. I've just amended that. Also added the existing `fixture.mpg` to the tests, as it was missing.

**Pull request merged**
