### PR TITLE
xo and ava versions. Use ./node_modules/xo/cli.js && ./node_modules/a…

### PR DESCRIPTION
**Pull request by yagop**
`xo` and `ava` versions in `package.json`. Use `./node_modules/xo/cli.js && ./node_modules/ava/cli.js` for tests.

### CODE REVIEW

**Comment by sindresorhus** [comment]
No, there's no point. The current way works fine.

**Comment by yagop** [comment]
Current way works fine but requires `xo` and `ava` installed globally and not many modules uses them.

**Comment by kevva** [comment]
Only Windows needs the absolute path. OS X and Linux resolves to the locally installed one.

**Comment by sindresorhus** [comment]
npm prepends locally installed binaries to the PATH so you can run them by name. No need to globally install.

**Comment by kevva** [comment]
Except, on Windows it doesn't, surprise surprise.

**Comment by yagop** [comment]
Oh it's true, thanks :sweat_smile:

**Pull request closed without merging**
