### PR TITLE
cache node_modules dir

### PR DESCRIPTION
**Pull request by yagop**
Travis cache `node_modules` dir

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. No point. Travis is fast enough and there are downsides with using a cache.

**Comment by yagop** [comment]
I cant see the downside of using a cached version of `node_modules` for your project. The last Travis job took 59.25s doing the `npm install` which is about 80% (1 min 14 sec).

**Comment by sindresorhus** [comment]
When I run Travis I want to test on a fresh npm install. What if a sub-sub-dependency breaks in a patch version, but it's cached. Then Travis will pass, but will be broken for the user. Not worth the minor speed improvement.

**Comment by yagop** [comment]
I see :+1:

**Pull request closed without merging**
