### PR TITLE
Allow `ArrayBuffer` as input

### LINKED ISSUE #191: Input validation breaks ArrayBuffer
Turns out this change ba2fdde5fa4350d46f2f8c50e8bafe73f3a5a2d3

```js
	if (!(input instanceof Uint8Array || Buffer.isBuffer(input))) {
		throw new TypeError(`Expected the \`input\` argument to be of type \`Uint8Array\` or \`Buffer\`, got \`${typeof input}\``);
	}
```

is backward incompatible with this package: https://github.com/dy/image-decode/blob/master/index.js#L10

Is there a reason this cannot support `ArrayBuffer`? Otherwise can you add that to the type check as valid input?

### PR DESCRIPTION
**Pull request by razor-x**
Closes #191

### CODE REVIEW

**Comment by razor-x** [comment]
@sindresorhus Anything else you need for a merge / release?

**Comment by sindresorhus** [comment]
You also need to update the readme.

**Comment by razor-x** [comment]
Cool. I've updated all the spots that mentioned `Uint8Array` to include `ArrayBuffer`.

**Comment by razor-x** [comment]
I'm not familiar with typescript, any thoughts on the CI error :|

```
  index.test-d.ts:8:59
  ✖  8:59  Argument of type number[] is not assignable to parameter of type number.  
  1 error
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
```

**Comment by sindresorhus** [comment]
@razor-x Read the error. `ArrayBuffer` accepts a `length` (number) argument, not an array.

**Comment by razor-x** [comment]
Thanks :) Your translation is much clearer.

**Pull request merged**
