### PR TITLE
new rule updates from xo 0.40.2

### PR DESCRIPTION
**Pull request by jimmywarting**
xo haven't been updated for a while, it came with a bunch of new rules
Tried fixing most of them

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but I don't plan to target Node.js 10. The next major release will target Node.js 12 and move to ESM, but I'm not ready to do that yet.

**Comment by jimmywarting** [comment]
> The next major release will target Node.js 12 and move to ESM

I would like that, very much

> but I'm not ready to do that yet.

Anything i can help to speed up the process? update any sub dependency or anything?

**Comment by sindresorhus** [comment]
> Anything i can help to speed up the process? update any sub dependency or anything?

I was excited to move all my packages to ESM, but it just caused too many problems. Bundlers were not ready and I cannot spend all my time closing issues about ESM. So I have put the ESM move on a break for a month or two.

**Comment by sindresorhus** [comment]
CI is failing, btw.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/file-type/commit/826b4addf8d3aebe37faf8465897f90c76a82e99.

**Pull request closed without merging**
