### PR TITLE
Add `ktx` (Khronos compressed textures)

### PR DESCRIPTION
**Pull request by paraboul**
Support for Khronos compressed textures (ktx), as defined by https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/

### CODE REVIEW

**Comment by sindresorhus** [comment]
It also needs to be added to the readme. Example: https://github.com/sindresorhus/file-type/commit/1160422530ae3709997a4aaa131124e342ce0e56

**Comment by paraboul** [comment]
done.

**Comment by paraboul** [comment]
Should I bump the version number?

**Comment by sindresorhus** [comment]
No

**Pull request merged**
