### PR TITLE
Add support for Apache Parquet

### PR DESCRIPTION
**Pull request by bencmbrook**
Closes https://github.com/sindresorhus/file-type/issues/575

Official Documentation (with magic number documented here): https://parquet.apache.org/docs/file-format/

### CODE REVIEW

**Comment by bencmbrook** [comment]
Test failures appear to be this upstream issue https://github.com/xojs/xo/issues/546. Locally had the same thing, but `npx ava` passes.

**Comment by sindresorhus** [comment]
https://github.com/import-js/eslint-plugin-import/pull/2664

**Review by sindresorhus — APPROVED** [review]

**Review by Borewit — CHANGES_REQUESTED** [review]
Code changes are looking good.

@bencmbrook is it possible to use a smaller fixture (without truncating it)?

**Comment by bencmbrook** [comment]
@Borewit yup - good call! Replaced it with a much smaller fixture

**Pull request merged**
