### PR TITLE
Add FLIF support

### PR DESCRIPTION
**Pull request by odilitime**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please see previous additions on what's required to add a new file format. https://github.com/sindresorhus/file-type/commit/b02ed7521059f67d71ca491f6854ea40075593ce Also provide some source of the magic number you used.

**Comment by odilitime** [comment]
"b02ed75 Also provide some source of the magic number you used."
Uh what?
ME: "if (buf[0] === 0x46 && buf[1] === 0x4C && buf[2] === 0x49 && buf[3] === 0x46) {"

Them: "if (buf[28] === 0x4F && buf[29] === 0x70 && buf[30] === 0x75 && buf[31] === 0x73 && buf[32] === 0x48 && buf[33] === 0x65 && buf[34] === 0x61 && buf[35] === 0x64) {"
Not same positions or hex values.

**Comment by t1st3** [comment]
@odilitime I think the commit referenced by @sindresorhus was given to give you an example of what to do to fulfill your PR; the signature for `flif` files you suggest is obviously different from the signature of the `opus` files provided in the example commit.
Then, you updated `package.json`, but you'll still need to update the `readme.md` and create a test. And finally, please provide some link here to where you got that signature.

**Comment by odilitime** [comment]
Yup read what he wrote wrong, all supporting files are there

**Pull request closed without merging**
