### PR TITLE
Add Extensions set for supported file extension/ MIME type lookup

### LINKED ISSUE #91: isSupported() method
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/file-type/issues/91)

It'd be nice to have a function that returns if input extension (string) is supported by the module

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($20.00)
### Submitted pull Requests
- [#229 added fileType.extensions and fileType.mimeTypes properties](https://issuehunt.io/r/sindresorhus/file-type/pull/229)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/file-type/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by jeswinsimon**
Fixes #91

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read the issue thread more closely:

> I think we instead should just expose **a list (Set type) of supported extensions and one with mime types.**

**Comment by sindresorhus** [comment]
You also need to add tests and add it to https://github.com/sindresorhus/file-type/blob/master/index.d.ts

**Comment by sindresorhus** [comment]
And it should probably be a getter that returns a new Set each time so users can't accidentally modify the Set.

**Comment by sindresorhus** [comment]
You also need to update for https://github.com/sindresorhus/file-type/commit/feaa2178e70b2c71a9027461c4aebca86e529ef5

**Comment by jeswinsimon** [comment]
Tests are pending. I will add them soon.

**Comment by sindresorhus** [comment]
Ping

You also need to update from master again. New file types were added.

**Pull request closed without merging**
