### PR TITLE
Add support for MPEG-4 Audiobook (.m4b)

### LINKED ISSUE #165: m4b audio books maps to video/mp4
Ref: 
- https://en.wikipedia.org/wiki/MPEG-4_Part_14
- https://en.wikipedia.org/wiki/Audio_file_format

Related issues:
- #147 _MPEG-4 Audio maps to wrong MIME-type_
- #122: _m4a from android phone_
- #99: _Many MP4 variants are not implemented_

### PR DESCRIPTION
**Pull request by Borewit**
Fixes #165
Related: #99, #60, #38

Note that I removed `check([0x4D, 0x34, 0x41, 0x20])`, at offset 0. I don't think this picking out any MPEG-4 audio file.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests are failing as the audiobook fixture is being detected as `.mp4`.

**Comment by Borewit** [comment]
Not sure if it is actually that simple to pick out the `.m4b` extension.

**Comment by sindresorhus** [comment]
@Borewit Still interested in finishing this? :)

**Comment by Borewit** [comment]
You may close the issue.
I don't think there is a feasible way to extract the audio-book type.
Although this can be found in the metadata, the complexity to get that out with the risk it might not be within the first 4k, I don't think it's worth to implement it.

I started this PR based on the assumption it could be extracted with the first bytes, which appears not to be the case.

I went through the changes of this PR, and kept a minor code correction, which I moved to [PR](https://github.com/sindresorhus/file-type/pull/184).

I use this module for [music-metadata](https://github.com/Borewit/music-metadata) to determine the audio file type, based on the content, as a fallback in case the audio type wasn't provided by the user. As long as I get one of the  MPEG-4 MIME-types it works for me.

Feel free to ping me on any discussion regarding audio file type, or on requests to cover new audio file types.

**Comment by sindresorhus** [comment]
I understand. No worries at all :)

> Feel free to ping me on any discussion regarding audio file type, or on requests to cover new audio file types.

Will do.

**Pull request closed without merging**
