### PR TITLE
Add MXF format

### PR DESCRIPTION
**Pull request by seanmtracey**
Common format for media professionals to store video/audio, and has [magic numbers](http://www.digitalpreservation.gov/formats/fdd/fdd000013.shtml).

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you add it to the readme too.

**Comment by seanmtracey** [comment]
Absolutely :) Done.

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by seanmtracey** [comment]
You're welcome :)

**Pull request merged**
