### PR TITLE
Add support for COFF (Unix Common Object File Format)

### PR DESCRIPTION
**Pull request by votruongan**
**File magic number reference:** [https://en.wikipedia.org/wiki/COFF](https://en.wikipedia.org/wiki/COFF)

**MIME type:** I have looked up in [IANA's list](https://www.iana.org/assignments/media-types/media-types.xhtml) and [tika supported MIME types](https://tika.learnworlds.com/mime-types), but couldn't find any MIME type associated with COFF, so I left `application/octet-stream` as default.

If you're adding support for a new file type, please follow the below steps:
- **One PR per file type.**
- [x] Add a fixture file named `fixture.<extension>` to the `fixture` directory.
- [x] Add the file extension to the `extensions` array in `supported.js`.
- [x] Add the file's MIME type to the `types` array in `supported.js`.
- [x] Add the file type detection logic to the `core.js` file.
- [x] Add the file extension to the `FileType` type in `core.d.ts`.
- [x] Add the file's MIME type to the `MimeType` type in `core.d.ts`.
- [x] Add the file extension to the `Supported file types` section in the readme, in the format ```- [`<extension>`](URL) - Format name```, for example, ```- [`png`](https://en.wikipedia.org/wiki/Portable_Network_Graphics) - Portable Network Graphics```
- [x] Add the file extension to the `keywords` array in the `package.json` file.
- [x] Run `$ npm test` to ensure the tests pass.
- [x] Open a pull request with a title like `Add support for Format`, for example, `Add support for PNG`.
- [x] The pull request description should include a link to the official page of the file format or some other source. Also include a link to where you found the file type detection / magic bytes and the MIME type.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Do you actually need this? Wikipedia says the format is mostly replaced by ELF.

**Comment by votruongan** [comment]
No, my needs haven't touched any COFF file yet. I am just adding support for as much executable files as possible.

COFF is deprecated, but its extended version, like XCOFF (different magic number) is still able to run on IBM AIX systems, so I think I would also open a PR for XCOFF.

So, supporting COFF in this package is much more about diversity and historical purpose. other types of COFF would have more practical impacts.

**Comment by sindresorhus** [comment]
> So, supporting COFF in this package is much more about diversity and historical purpose.

The goal of this package is to support commonly used formats, not everything. For historical or little used formats, it's better to just spawn the `file` command.

**Comment by sindresorhus** [comment]
> COFF is deprecated, but its extended version, like XCOFF (different magic number) is still able to run on IBM AIX systems, so I think I would also open a PR for XCOFF.

I'm going to pass on that one too. It's enough work to maintain popular modern formats. I don't want to open the flood gates for everything out there.

**Pull request closed without merging**
